"""m3 document summary

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-07 12:12:36.094307
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JSONB_VARIANT = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("so_gp", sa.String(length=64), nullable=True))
    op.add_column("documents", sa.Column("ngay_cap", sa.Date(), nullable=True))
    op.add_column("documents", sa.Column("summary", JSONB_VARIANT, nullable=False, server_default="{}"))
    op.create_index(op.f("ix_documents_ngay_cap"), "documents", ["ngay_cap"], unique=False)
    op.create_index(op.f("ix_documents_so_gp"), "documents", ["so_gp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_so_gp"), table_name="documents")
    op.drop_index(op.f("ix_documents_ngay_cap"), table_name="documents")
    op.drop_column("documents", "summary")
    op.drop_column("documents", "ngay_cap")
    op.drop_column("documents", "so_gp")
    # ### end Alembic commands ###
